jekyll:
  image: jekyll/jekyll:pages
  command: bash -c "apk add --no-cache g++ gcc make musl-dev && gem install eventmachine && bundle update && bundle exec jekyll serve --watch --incremental"
  ports:
    - "0.0.0.0:4000:4000"
  volumes:
    - .:/srv/jekyll
